# Generated by Django 4.1.7 on 2023-05-24 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameHomePlayers',
            new_name='GameHomePlayer',
        ),
        migrations.RenameModel(
            old_name='GameVisitorPlayers',
            new_name='GameVisitorPlayer',
        ),
        migrations.AlterModelTable(
            name='gamehomeplayer',
            table='game_home_player',
        ),
        migrations.AlterModelTable(
            name='gamevisitorplayer',
            table='game_visitor_player',
        ),
    ]
