# Generated by Django 4.1.7 on 2023-05-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0003_game_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamevisitorplayer',
            name='id',
            field=models.CharField(max_length=21, primary_key=True, serialize=False),
        ),
    ]
