# Generated by Django 4.1.7 on 2023-06-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0004_alter_gamevisitorplayer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameAux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_game', models.CharField(max_length=12, null=True)),
                ('type', models.CharField(max_length=4, null=True)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('visitor_team', models.CharField(max_length=3, null=True)),
                ('home_team', models.CharField(max_length=3, null=True)),
                ('prev_game', models.CharField(max_length=12, null=True)),
                ('tp_f', models.PositiveSmallIntegerField(null=True)),
                ('tpp_f', models.DecimalField(decimal_places=9, max_digits=10, null=True)),
                ('dp_f', models.PositiveSmallIntegerField(null=True)),
                ('dpp_f', models.DecimalField(decimal_places=9, max_digits=10, null=True)),
                ('ft_f', models.PositiveSmallIntegerField(null=True)),
                ('ftp_f', models.DecimalField(decimal_places=9, max_digits=10, null=True)),
                ('tp_c', models.PositiveSmallIntegerField(null=True)),
                ('tpp_c', models.DecimalField(decimal_places=9, max_digits=10, null=True)),
                ('dp_c', models.PositiveSmallIntegerField(null=True)),
                ('dpp_c', models.DecimalField(decimal_places=9, max_digits=10, null=True)),
                ('ft_c', models.PositiveSmallIntegerField(null=True)),
                ('ftp_c', models.DecimalField(decimal_places=9, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'game_aux',
            },
        ),
    ]
