# Generated by Django 4.1.7 on 2023-06-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0005_gameaux'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
