# Generated by Django 4.1.7 on 2023-06-14 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0007_rename_text_team_old_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameAux',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='date',
            new_name='game_date',
        ),
    ]
