# Generated by Django 4.1.7 on 2023-06-14 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0008_delete_gameaux_rename_date_game_game_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='time',
            new_name='game_time',
        ),
    ]
