# Generated by Django 4.1.7 on 2023-06-14 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0009_rename_time_game_game_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foulplay',
            old_name='time',
            new_name='play_time',
        ),
        migrations.RenameField(
            model_name='freethrowplay',
            old_name='time',
            new_name='play_time',
        ),
        migrations.RenameField(
            model_name='reboundplay',
            old_name='time',
            new_name='play_time',
        ),
        migrations.RenameField(
            model_name='substitutionplay',
            old_name='time',
            new_name='play_time',
        ),
        migrations.RenameField(
            model_name='threepointerplay',
            old_name='time',
            new_name='play_time',
        ),
        migrations.RenameField(
            model_name='turnoverplay',
            old_name='time',
            new_name='play_time',
        ),
        migrations.RenameField(
            model_name='twopointerplay',
            old_name='time',
            new_name='play_time',
        ),
    ]
