# Generated by Django 4.1.7 on 2023-06-14 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0010_rename_time_foulplay_play_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='mp',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
