# Generated by Django 4.1.7 on 2023-06-14 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0011_alter_player_mp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerhist',
            name='mp',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
